/**
 * Centralized Application Strings & UI Copy
 * Sofiya Bangles Mobile Customer App
 * Single Source of Truth for all user-facing text
 * Adheres to UI/UX Design Constitution (Localization Readiness)
 */

export const STRINGS = {
  common: {
    appName: 'Sofiya Bangles',
    back: 'Go back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    refresh: 'Refresh',
    refreshNow: 'Refresh Now',
    clear: 'Clear',
    clearSearch: 'Clear Search',
    seeAll: 'See All',
    exploreNow: 'Explore Now',
    browseAll: 'Browse All',
    search: 'Search',
    filter: 'Filter',
    quantity: 'Quantity',
    price: 'Price',
    description: 'Description',
    code: 'Code',
    bought: 'Bought',
    soldOut: 'Sold Out',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    madeToOrder: 'Made to Order',
    custom: 'Custom',
    all: 'All',
    allSizes: 'All Sizes',
    share: 'Share product',
    favorite: 'Favorite',
    whatsApp: 'WhatsApp',
    edit: 'Edit',
    decreaseQuantity: 'Decrease quantity',
    increaseQuantity: 'Increase quantity',
    markBoughtA11y: 'Mark product as bought',
  },

  tabs: {
    home: 'Home',
    collections: 'Collections',
    favorites: 'Favorites',
    notifications: 'Notifications',
    profile: 'Profile',
  },

  home: {
    greeting: 'Welcome back,',
    tagline: 'Find best suited things for you',
    roles: {
      user: 'User',
      admin: 'Admin',
      superAdmin: 'Super Admin',
    },
    actions: {
      viewOrders: 'View orders',
      viewProfile: 'View profile',
    },
    banners: {
      newArrivals: {
        id: 'new-arrivals',
        badge: 'JUST DROPPED ✨',
        title: 'New Arrivals',
        subtitle: 'Explore latest handcrafted designs & fresh styles',
        buttonText: 'Explore Now',
        route: '/new-arrivals',
      },
      collections: {
        id: 'categories',
        badge: 'COLLECTIONS 🌟',
        title: 'Trending Styles',
        subtitle: 'Bridal, daily wear & festive bangle collections',
        buttonText: 'Browse All',
        route: '/(tabs)/categories',
      },
      sizePreferences: {
        id: 'size-preferences',
        badge: 'CUSTOM TAILORED 📏',
        title: 'Perfect Fit Guide',
        subtitle: 'Set your custom size for tailored bangle fittings',
        buttonText: 'Set My Size',
        route: '/(tabs)/size-preferences',
      },
    },
    sections: {
      collections: 'Collections',
      recommended: 'Recommended',
    },
    searchPlaceholder: 'Search bangles, styles, collections...',
    searchResults: (query: string) => `Results for "${query}"`,
    filterBySize: 'Filter by Size',
    mySizePreferences: 'My Size Preferences',
    states: {
      loadingRecommendations: 'Loading recommendations...',
      noProductsTitle: 'No products found',
      noProductsDescription: 'Pull down to refresh or check our collections above.',
      noSearchTitle: 'No matching bangles found',
      noSearchDescription: (query: string) =>
        `We couldn't find any products matching "${query}". Try a different keyword or browse collections.`,
    },
  },

  collections: {
    title: 'Collections',
    searchPlaceholder: 'Search collections...',
    loading: 'Loading collections...',
    emptyTitle: 'No collections found',
    emptyDescription: (query: string) => `We couldn't find any collections matching "${query}"`,
    seeAll: 'See All',
  },

  categoryProducts: {
    loading: (name: string) => `Loading ${name}...`,
    searchPlaceholder: (name: string) => `Search ${name}...`,
    allSizes: 'All Sizes',
    mySize: (size: string) => `My Size: ${size}`,
    sizeLabel: (size: string) => `Size ${size}`,
    customFilter: 'Custom',
    emptySizeTitle: 'No Products in this Size',
    emptyGeneralTitle: 'No Products Yet',
    emptySizeDescription: (size: string) =>
      `There are currently no products available in ${size}. Try selecting All Sizes.`,
    emptyGeneralDescription: (name: string) =>
      `We're currently restocking our ${name} collection. Check back soon!`,
    viewAllSizes: 'View All Sizes',
    exploreOtherStyles: 'Explore Other Styles',
  },

  productDetail: {
    notAvailableTitle: 'Product Not Available',
    notAvailableDescription:
      'This product has been removed or is no longer available.\nIt may have been deleted by the store admin.',
    goBack: 'Go Back',
    browseProducts: 'Browse Products',
    codePrefix: 'Code: ',
    quantityLabel: 'Quantity',
    descriptionLabel: 'Description',
    noDescription: 'No description provided.',
    markAsBought: 'Mark as Bought',
    inquireWhatsApp: 'Inquire on WhatsApp',
    orderSuccessTitle: 'Saved',
    orderSuccessMessage: 'This product is now in your orders list.',
    orderErrorTitle: 'Error',
    orderErrorMessage: 'Could not save this purchase.',
    reviewThanksTitle: 'Thanks!',
    reviewThanksMessage: 'Your review has been added.',
    reviewErrorMessage: 'Could not save the review.',
    reviewsTitle: 'Reviews',
    reviewCount: (count: number) => `${count} review(s)`,
    noReviews: 'No reviews yet.',
    damageNotePrefix: 'Damage note: ',
    ratePurchaseTitle: 'Rate this purchase',
    ratePurchaseSubtitle: 'Share how it felt and any notes.',
    shareExperiencePlaceholder: 'Share your experience with this product',
    damagePlaceholder: 'Any damage or issues? (optional)',
    selectSizeTitle: 'Select Size',
    modelSizesTitle: (model: string) => `${model} Sizes`,
    customMadeToOrder: 'Custom Made to Order',
    customMadeToOrderSubtitle: "We'll craft this perfectly to your measurements.",
    selectProfileTitle: 'SELECT CUSTOM SIZE PROFILE',
    defaultProfileName: 'Custom Profile',
    customFitTitle: (name: string) => `Measurements for ${name}`,
    noCustomMeasurements: 'No custom measurements saved for this collection.',
    addMeasurementsNow: 'Add Measurements Now',
    submitReview: 'Submit Review',
    reviewSaved: 'Review saved successfully.',
  },

  favorites: {
    title: 'Favorites',
    emptyTitle: 'No favorites yet',
    emptyDescription: 'Explore our collections and tap the heart icon on any product to save your favorites here.',
    exploreCollections: 'Explore Collections',
    removeAccessibility: 'Remove from favorites',
    addAccessibility: 'Add to favorites',
  },

  newArrivals: {
    title: 'New Arrivals',
    filterSubtitle: 'Filter by recent drops',
    past24Hours: 'Past 24 Hours',
    past5Days: 'Past 5 Days',
    past7Days: 'Past 7 Days',
    loading: 'Fetching the latest pieces...',
    emptyTitle: 'No Recent Drops',
    emptyDescription: "We haven't added any new products in the selected timeframe.",
  },
} as const;
