/**
 * Centralized Application Strings & UI Copy
 * Sofiya Bangles Mobile Customer App
 * Single Source of Truth for all user-facing text
 * Adheres to UI/UX Design Constitution (Localization Readiness)
 */

export const STRINGS = {
  common: {
    appName: 'Sofiya Bangles',
    back: 'Go back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    refresh: 'Refresh',
    refreshNow: 'Refresh Now',
    clear: 'Clear',
    clearSearch: 'Clear Search',
    seeAll: 'See All',
    exploreNow: 'Explore Now',
    browseAll: 'Browse All',
    search: 'Search',
    filter: 'Filter',
    quantity: 'Quantity',
    price: 'Price',
    description: 'Description',
    code: 'Code',
    design: 'Design',
    stock: 'Stock',
    sizes: 'Sizes',
    type: 'Type',
    bought: 'Bought',
    soldOut: 'Sold Out',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    lowStock: (count: number) => `Only ${count} left`,
    madeToOrder: 'Made to Order',
    custom: 'Custom',
    all: 'All',
    allSizes: 'All Sizes',
    share: 'Share product',
    favorite: 'Favorite',
    whatsApp: 'WhatsApp',
    edit: 'Edit',
    decreaseQuantity: 'Decrease quantity',
    increaseQuantity: 'Increase quantity',
    markBoughtA11y: 'Mark product as bought',
  },

  tabs: {
    home: 'Home',
    collections: 'Collections',
    favorites: 'Favorites',
    notifications: 'Notifications',
    profile: 'Profile',
  },

  home: {
    greeting: 'Welcome back,',
    tagline: 'Find best suited things for you',
    roles: {
      user: 'User',
      admin: 'Admin',
      superAdmin: 'Super Admin',
    },
    actions: {
      viewOrders: 'View orders',
      viewProfile: 'View profile',
    },
    banners: {
      newArrivals: {
        id: 'new-arrivals',
        badge: 'JUST DROPPED ✨',
        title: 'New Arrivals',
        subtitle: 'Explore latest handcrafted designs & fresh styles',
        buttonText: 'Explore Now',
        route: '/new-arrivals',
      },
      collections: {
        id: 'categories',
        badge: 'COLLECTIONS 🌟',
        title: 'Trending Styles',
        subtitle: 'Bridal, daily wear & festive bangle collections',
        buttonText: 'Browse All',
        route: '/(tabs)/categories',
      },
      sizePreferences: {
        id: 'size-preferences',
        badge: 'CUSTOM TAILORED 📏',
        title: 'Perfect Fit Guide',
        subtitle: 'Set your custom size for tailored bangle fittings',
        buttonText: 'Set My Size',
        route: '/(tabs)/size-preferences',
      },
    },
    sections: {
      collections: 'Collections',
      recommended: 'Recommended',
    },
    searchPlaceholder: 'Search bangles, styles, collections...',
    searchResults: (query: string) => `Results for "${query}"`,
    filterBySize: 'Filter by Size',
    mySizePreferences: 'My Size Preferences',
    states: {
      loadingRecommendations: 'Loading recommendations...',
      noProductsTitle: 'No products found',
      noProductsDescription: 'Pull down to refresh or check our collections above.',
      noSearchTitle: 'No matching bangles found',
      noSearchDescription: (query: string) =>
        `We couldn't find any products matching "${query}". Try a different keyword or browse collections.`,
    },
  },

  collections: {
    title: 'Collections',
    searchPlaceholder: 'Search collections...',
    loading: 'Loading collections...',
    emptyTitle: 'No collections found',
    emptyDescription: (query: string) => `We couldn't find any collections matching "${query}"`,
    seeAll: 'See All',
  },

  categoryProducts: {
    loading: (name: string) => `Loading ${name}...`,
    searchPlaceholder: (name: string) => `Search ${name}...`,
    allSizes: 'All Sizes',
    mySize: (size: string) => `My Size: ${size}`,
    sizeLabel: (size: string) => `Size ${size}`,
    customFilter: 'Custom',
    emptySizeTitle: 'No Products in this Size',
    emptyGeneralTitle: 'No Products Yet',
    emptySizeDescription: (size: string) =>
      `There are currently no products available in ${size}. Try selecting All Sizes.`,
    emptyGeneralDescription: (name: string) =>
      `We're currently restocking our ${name} collection. Check back soon!`,
    viewAllSizes: 'View All Sizes',
    exploreOtherStyles: 'Explore Other Styles',
  },

  productDetail: {
    notAvailableTitle: 'Product Not Available',
    notAvailableDescription:
      'This product has been removed or is no longer available.\nIt may have been deleted by the store admin.',
    goBack: 'Go Back',
    browseProducts: 'Browse Products',
    codePrefix: 'Code: ',
    quantityLabel: 'Quantity',
    descriptionLabel: 'Description',
    noDescription: 'No description provided.',
    markAsBought: 'Mark as Bought',
    inquireWhatsApp: 'Inquire on WhatsApp',
    orderSuccessTitle: 'Saved',
    orderSuccessMessage: 'This product is now in your orders list.',
    orderErrorTitle: 'Error',
    orderErrorMessage: 'Could not save this purchase.',
    reviewThanksTitle: 'Thanks!',
    reviewThanksMessage: 'Your review has been added.',
    reviewErrorMessage: 'Could not save the review.',
    reviewsTitle: 'Reviews',
    reviewCount: (count: number) => `${count} review(s)`,
    noReviews: 'No reviews yet.',
    damageNotePrefix: 'Damage note: ',
    ratePurchaseTitle: 'Rate this purchase',
    ratePurchaseSubtitle: 'Share how it felt and any notes.',
    shareExperiencePlaceholder: 'Share your experience with this product',
    damagePlaceholder: 'Any damage or issues? (optional)',
    selectSizeTitle: 'Select Size',
    modelSizesTitle: (model: string) => `${model} Sizes`,
    customMadeToOrder: 'Custom Made to Order',
    customMadeToOrderSubtitle: "We'll craft this perfectly to your measurements.",
    selectProfileTitle: 'SELECT CUSTOM SIZE PROFILE',
    defaultProfileName: 'Custom Profile',
    customFitTitle: (name: string) => `Measurements for ${name}`,
    noCustomMeasurements: 'No custom measurements saved for this collection.',
    addMeasurementsNow: 'Add Measurements Now',
    submitReview: 'Submit Review',
    reviewSaved: 'Review saved successfully.',
  },

  favorites: {
    title: 'Favorites',
    emptyTitle: 'No favorites yet',
    emptyDescription: 'Explore our collections and tap the heart icon on any product to save your favorites here.',
    exploreCollections: 'Explore Collections',
    removeAccessibility: 'Remove from favorites',
    addAccessibility: 'Add to favorites',
  },

  newArrivals: {
    title: 'New Arrivals',
    filterSubtitle: 'Filter by recent drops',
    past24Hours: 'Past 24 Hours',
    past5Days: 'Past 5 Days',
    past7Days: 'Past 7 Days',
    loading: 'Fetching the latest pieces...',
    emptyTitle: 'No Recent Drops',
    emptyDescription: "We haven't added any new products in the selected timeframe.",
  },

  admin: {
    tabs: {
      dashboard: 'Dashboard',
      products: 'Products',
      add: 'Add',
      collections: 'Collections',
      settings: 'Settings',
    },
    quickActions: {
      addProduct: 'Add Product',
      manageProducts: 'Manage',
      collections: 'Collections',
      modelTypes: 'Model Types',
    },
    collections: {
      title: 'Collections',
      collection: 'Collection',
      collectionNotFound: 'Collection not found',
      badge: 'Admin Panel',
      addTitle: 'Add New Collection',
      editTitle: 'Edit Collection',
      nameLabel: 'Collection Name *',
      namePlaceholder: 'e.g. Silk Thread, Velvet, Glass',
      modelTypeLabel: 'Model Type *',
      selectModelType: 'Select Model Type',
      imageLabel: 'Collection Image',
      changePhoto: 'Change Photo',
      uploadPhoto: 'Upload Photo',
      standardSizesLabel: 'Standard Sizes for this Collection *',
      standardSizesPlaceholder: 'e.g. 2.4, 2.6, 2.8',
      standardSizesHint: 'Separate sizes with commas. Sizing rules are standardized per collection.',
      cancel: 'Cancel',
      save: 'Save Collection',
      saveBtn: 'Save',
      createSuccess: 'Collection created successfully.',
      updateSuccess: 'Collection updated successfully.',
      deleteConfirmTitle: 'Delete Collection',
      deleteConfirmMsg: 'Are you sure you want to delete this collection?',
      deleteSuccess: 'Collection deleted successfully.',
      noCollections: 'No collections found. Tap + to add one.',
      loading: 'Loading collections...',
      all: 'All Collections',
      filterLabel: 'Filter by Collection',
      enterCollectionName: 'Please enter a name for the Collection.',
      selectModelTypePrompt: 'Please select a Model Type or create a new one.',
      enterModelTypeName: 'Please enter a name for the new Model Type.',
      enterStandardSize: 'Please enter at least one standard size.',
      stepDetails: 'Step 2: Collection Details',
      stepSizing: 'Step 3: Collection Sizing',
      modelTypeSelectOrCreate: 'Select or Create Model Type',
      defineNewModelType: 'Define New Model Type',
      uploadImageHint: 'Tap to upload image',
    },
    products: {
      categorization: 'Collections & Model',
      selectCollection: 'Select Collection *',
      noCollectionsFound: 'No collections found for this model.',
      pleaseSelectCollection: 'Please select a collection',
      filterAll: 'All',
      noProductsYet: 'No products yet',
      totalProducts: (count: number) => `${count} total products`,
    },
  },

  auth: {
    otpVerify: {
      badge: 'Two-Factor Security',
      title: 'Two-Factor Verification',
      recoveryTitle: 'Recovery Code Sign In',
      subtitle: 'Enter the 6-digit code generated by your authenticator app.',
      recoverySubtitle: 'Enter one of your single-use backup recovery codes.',
      codeLabel: 'Security Code',
      recoveryCodeLabel: 'Backup Recovery Code',
      recoveryPlaceholder: 'e.g. ABCD-1234',
      recoveryHint: 'Case-insensitive. Dashes are optional.',
      refreshesIn: (seconds: number) => `Code refreshes in ${seconds}s`,
      rotatingSoon: (seconds: number) => `Rotating in ${seconds}s...`,
      verifyBtn: 'Verify & Sign In',
      verifyRecoveryBtn: 'Verify Recovery Code',
      useRecovery: 'Lost your device? Use Backup Recovery Code',
      useAuthenticator: 'Use Authenticator App instead',
      accountLocked: 'Account Temporarily Locked',
      defaultLockout: 'Too many failed attempts. Your account has been locked for 15 minutes.',
      clear: 'Clear',
    },
    qrSetup: {
      badge: 'Step 1 of 2',
      title: 'Set Up Authenticator',
      subtitle: 'Scan this QR code with Google Authenticator or your preferred 2FA app.',
      secretKeyLabel: 'Secret Key (Manual Entry)',
      copied: 'Copied to clipboard!',
      tapToCopy: 'Tap to copy key',
      enterCodeTitle: 'Step 2: Enter Verification Code',
      enterCodeSubtitle: 'Enter the 6-digit code from your authenticator app to confirm setup.',
      refreshesIn: (seconds: number) => `Code refreshes in ${seconds}s`,
      rotatingSoon: (seconds: number) => `Rotating in ${seconds}s...`,
      verifyAndActivate: 'Verify & Activate 2FA',
      regenerate: 'Regenerate QR Code',
      expiredTitle: 'QR Code Expired',
      expiredSubtitle: 'For security, QR codes expire after 5 minutes. Tap below to generate a new one.',
      cancel: 'Cancel Setup',
    },
    backupCodes: {
      badge: 'Step 2 of 2',
      title: 'Save Recovery Codes',
      subtitle: 'Save these 10 recovery codes now. They will never be displayed again.',
      warning: 'Each recovery code can only be used once if you lose access to your authenticator.',
      copyAll: 'Copy All Codes',
      copiedAll: 'All codes copied!',
      confirmCheckbox: 'I have safely stored these recovery codes',
      continueToDashboard: 'Continue to Dashboard',
    },
  },
} as const;
