/**
 * Centralized Application Strings & UI Copy Dictionary
 * Sofiya Bangles Web Admin Portal
 * Single Source of Truth for all text per UI/UX Design Constitution
 */

export const STRINGS = {
  common: {
    appName: 'Sofiya Bangles',
    adminPortal: 'Store Management Portal',
    save: 'Save',
    saving: 'Saving...',
    saved: 'Saved successfully',
    cancel: 'Cancel',
    delete: 'Delete',
    deleting: 'Deleting...',
    edit: 'Edit',
    create: 'Create',
    add: 'Add',
    back: 'Go back',
    close: 'Close',
    confirm: 'Confirm',
    status: 'Status',
    actions: 'Actions',
    search: 'Search',
    clearSearch: 'Clear search',
    filter: 'Filter',
    all: 'All',
    loading: 'Loading...',
    refresh: 'Refresh',
    quickSell: 'Quick Sell',
    view: 'View',
    signOut: 'Sign out',
    signingOut: 'Signing out...',
    logoutFailed: 'Logout failed',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    draft: 'Draft',
    active: 'Active',
    price: 'Price',
    quantity: 'Quantity',
    code: 'Code',
    description: 'Description',
  },

  navigation: {
    brandTitle: 'Sofiya Bangles',
    brandSubtitle: 'Store Management',
    overview: 'Overview',
    productsCatalog: 'Products Catalog',
    ordersWhatsApp: 'Orders & WhatsApp',
    collectionsCategories: 'Collections',
    modelTypes: 'Model Types',
    operationsLog: 'Product Operations Log',
    revenueLedger: '70/30 Revenue Ledger',
    staffAdmins: 'Staff Admins',
    googleForms: 'Google Forms',
    storeSettings: 'Store Settings',
    profile: 'Profile',
    security: 'Security',
    settings: 'Settings',
    notifications: 'Notifications',
    addNewBangles: 'Add New Bangles',
  },

  categories: {
    title: 'Collections',
    subtitle: (count: number) => `${count} collection${count === 1 ? '' : 's'} defined in catalog`,
    addCategory: 'Add Collection',
    editCategory: 'Edit Collection',
    deleteCategory: 'Delete Collection',
    categoryName: 'Collection Name',
    categoryNamePlaceholder: 'e.g. Bridal Collection, Glass Bangles, Matte Velvet',
    modelType: 'Model Type',
    selectModelType: 'Select a Model Type',
    standardSizes: 'Standard Sizes',
    standardSizesPlaceholder: 'e.g. 2.2, 2.4, 2.6, 2.8',
    standardSizesHelp: 'Comma-separated standard sizes available for products in this collection.',
    emptyTitle: 'No Collections Found',
    emptyDescription: 'Create your first bangle collection to organize products and define sizing models.',
    createdSuccess: 'Collection created successfully',
    updatedSuccess: 'Collection updated successfully',
    deletedSuccess: 'Collection deleted successfully',
    deleteConfirmTitle: 'Delete Collection',
    deleteConfirmMessage: (name: string) =>
      `Are you sure you want to delete "${name}"? Products under this collection may be affected. This action cannot be undone.`,
  },

  products: {
    title: 'Products Catalog',
    subtitle: (count: number) => `${count} total products in catalog`,
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    quickSellButton: 'Quick Sell by Code',
    searchPlaceholder: 'Search products by name, description or code (e.g. SIL-101)...',
    allCategories: 'All Collections',
    emptyTitle: 'No Products Found',
    emptyDescription: 'No products match your current search or collection filter. Try clearing your filters or add a new piece.',
    addFirstProduct: 'Add your first product',
    deleteConfirmTitle: 'Delete Product',
    deleteConfirmMessage: (name: string) =>
      `Are you sure you want to delete "${name}"? This action will remove it from the catalog and cannot be undone.`,
    deletedSuccess: 'Product deleted successfully',
  },

  modelTypes: {
    title: 'Model Types',
    subtitle: (count: number) => `${count} model type${count === 1 ? '' : 's'} configured`,
    addModelType: 'Add Model Type',
    editModelType: 'Edit Model Type',
    createModelType: 'Create Model Type',
    name: 'Model Type Name',
    namePlaceholder: 'e.g. Bangles, Rings, Necklaces',
    emptyTitle: 'No Model Types Found',
    emptyDescription: 'Create model types to categorize product sizing structures and variations.',
    deleteConfirmTitle: 'Delete Model Type',
    deleteConfirmMessage: (name: string) =>
      `Are you sure you want to delete model type "${name}"? This action cannot be undone.`,
    createdSuccess: 'Model type created successfully',
    updatedSuccess: 'Model type updated successfully',
    deletedSuccess: 'Model type deleted successfully',
  },

  orders: {
    title: 'Orders & WhatsApp',
    completeConfirmTitle: 'Complete Order',
    completeConfirmMessage:
      'Mark this order as COMPLETED? This allocates the 70/30 commission into the revenue ledger.',
  },

  admins: {
    title: 'Staff & Administrator Control',
    subtitle:
      'Manage store managers, configure staff permissions, and monitor security statuses.',
    addAdmin: 'Add Administrator',
    loadingStaff: 'Loading store staff...',
    superAdminRole: 'SuperAdmin',
    storeAdminRole: 'Store Admin',
    activeStatus: 'Active',
    disabledStatus: 'Disabled',
    noPhone: 'No phone registered',
    joinedPrefix: (date: string) => `Joined ${date}`,
    twoFactorLabel: 'Two-Factor Auth:',
    twoFactorConfigured: 'Configured',
    twoFactorNotSetUp: 'Not Set Up',
    deactivateBtn: 'Deactivate',
    activateBtn: 'Activate',
    deleteAdminTitle: 'Delete Administrator',
    modalTitle: 'Add New Administrator',
    modalSubtitle: 'Create a new store manager account.',
    fullNameLabel: 'Full Name *',
    fullNamePlaceholder: 'e.g. Ramesh Kumar',
    emailLabel: 'Email Address *',
    emailPlaceholder: 'admin@sofiyabangles.com',
    passwordLabel: 'Initial Password * (min 6 characters)',
    passwordPlaceholder: '••••••••',
    phoneLabel: 'Phone Number (Optional)',
    phonePlaceholder: '+919876543210',
    cancelBtn: 'Cancel',
    createAccountBtn: 'Create Admin Account',
    creatingAccountBtn: 'Creating...',
    superAdminCannotDeactivateToast: 'SuperAdmin accounts cannot be deactivated.',
    superAdminCannotDeleteToast: 'SuperAdmin accounts cannot be deleted.',
    requiredFieldsToast: 'Please fill in all required fields.',
    createdSuccessToast: 'New administrator created successfully!',
    toggleStatusSuccessToast: (statusText: string) =>
      `Admin ${statusText} successfully.`,
    deleteSuccessToast: 'Administrator deleted successfully.',
    deleteConfirmTitle: 'Delete Administrator',
    deleteConfirmMessage: (name: string, email: string) =>
      `Are you sure you want to delete ${name} (${email})? This action cannot be undone.`,
    toggleStatusConfirmTitle: (isActive: boolean) =>
      isActive ? 'Deactivate Administrator' : 'Activate Administrator',
    toggleStatusConfirmMessage: (name: string, isActive: boolean) =>
      isActive
        ? `Are you sure you want to deactivate ${name}? They will immediately be blocked from logging in.`
        : `Are you sure you want to activate ${name}? They will be able to log in.`,
  },

  notifications: {
    title: 'Notifications',
    newBadge: (count: number) => `${count} new`,
    empty: 'No notifications right now',
    markAsRead: 'Mark as read',
  },

  dialogs: {
    confirmTitle: 'Are you sure?',
    confirmDelete: 'Yes, Delete',
    confirmCancel: 'Cancel',
  },

  superAdminAuth: {
    accessRequiredTitle: 'SuperAdmin Access Required',
    accessRequiredDesc:
      'Accessing this administrative module is restricted to Super-Administrators.',
    formsAccessRequiredDesc:
      'Accessing external integration forms is restricted to Super-Administrators.',
    commissionAccessRequiredDesc:
      'Modifying platform 70/30 commission split parameters requires Super-Administrator credentials.',
    adminsAccessRequiredDesc:
      'Managing administrator accounts and security roles requires Super-Administrator credentials.',
    returnToDashboard: 'Return to Store Dashboard',
    accessRestrictedToast: 'Access restricted to Super Administrators',
  },

  adminDashboard: {
    welcome: (name: string) => `Welcome, ${name}`,
    subtitle:
      'Real-time bangles catalog management, inventory tracking & WhatsApp order fulfillment.',
    loadingDashboard: 'Loading dashboard...',
    addNewBangles: 'Add New Bangles',
    whatsAppSale: '+ WhatsApp Sale',
    catalogOverview: 'Catalog & Sales Overview',
    allModelTypes: 'All Model Types',
    allCategories: 'All Collections',
    totalProducts: 'Total Products',
    totalProductsDesc: 'Manage full catalog, descriptions & images',
    activeSuffix: 'Active',
    filteredSuffix: '(Filtered)',
    collectionsCategories: 'Collections',
    collectionsCategoriesDesc: 'Browse collections, standard sizes & models',
    ordersWhatsAppTitle: 'Orders & WhatsApp Sales',
    ordersWhatsAppDesc: 'Direct sales, customer logs & invoices',
    quickActionsTitle: 'Quick Management Actions',
    recentProductsTitle: 'Recently Added Bangles',
    viewAll: 'View all',
    noRecentProducts: 'No products added yet',
    stockAlertsTitle: 'Inventory Stock Alerts',
    stockAlertsEmpty: 'All items currently well stocked',
  },

  superAdminDashboard: {
    title: 'Revenue, Sales & Financial Analytics',
    subtitle:
      'Real-time 70/30 profit allocation, automated ledger audit & store performance metrics.',
    exportCsv: 'Export CSV',
    period7d: '7 Days',
    period30d: '30 Days',
    periodThisYear: 'This Year',
    grossSales: 'Gross Sales',
    grossSalesDesc: 'Total revenue generated',
    viewLedger: 'Ledger →',
    superAdminShare: 'SuperAdmin Share (30%)',
    platformRevenueDesc: 'Platform commission',
    viewDetails: 'Details →',
    adminShare: 'Admin Share (70%)',
    adminPayoutsDesc: 'Admin vendor payouts',
    netSales: 'Net Sales',
    refundsPrefix: (amount: number) => `Refunds: ₹${amount.toLocaleString('en-IN')}`,
    viewAudit: 'Audit →',
    productsSold: 'Products Sold',
    unitsSoldPrefix: (units: number) => `Units Sold: ${units}`,
    ordersAndBills: 'Orders & Bills →',
    activeCatalog: 'Active Catalog',
    totalCatalogPrefix: (total: number) => `Total Catalog: ${total}`,
    manageCatalog: 'Manage →',
    pendingOrders: 'Pending Orders',
    awaitingFulfillment: 'Awaiting fulfillment',
    dispatchOrders: 'Dispatch →',
    lowStockAlert: 'Low Stock Alert',
    outOfStockPrefix: (count: number) => `Out of stock: ${count}`,
    restockAlert: 'Restock →',
    trendTitle: 'Sales & Revenue Trend',
    trendSubtitle: 'Gross sales vs 70/30 revenue breakdown over time',
    viewRevenueLedger: 'View Revenue Ledger',
    noTrendData: 'No sales activity recorded in this time range.',
    legendGrossRevenue: 'Gross Revenue',
    legendAdminShare: 'Admin (70%)',
    legendSuperAdminShare: 'SuperAdmin (30%)',
    topProductsTitle: 'Top Performing Products',
    viewProducts: 'View Products',
    noTopProducts: 'No product sales yet.',
    unitsSoldSuffix: 'units sold',
    shareSuffix: 'share',
    recentSalesTitle: 'Recent Completed Sales',
    recentSalesSubtitle: 'Live order completions & 70/30 ledger splits',
    viewSalesLedgerBtn: 'View Sales Ledger →',
    tableOrderNumber: 'Order Number',
    tableCustomer: 'Customer',
    tableTotalAmount: 'Total Amount',
    tableAdminShare: 'Admin (70%)',
    tableSuperAdminShare: 'SuperAdmin (30%)',
    tableAction: 'Action',
    actionDetails: 'Details',
    noRecentSales: 'No completed sales records available.',
    categoryPerformanceTitle: 'Collection Performance',
    noCategoryMetrics: 'No collection metrics available.',
  },

  revenue: {
    title: 'Product Sales & Commission Ledger',
    subtitle: (adminPct: number, superPct: number) =>
      `Detailed record of which products sold at what rate, and the exact ${adminPct}% Admin vs ${superPct}% Super-Admin profit allocation.`,
    adjustRatio: 'Adjust Split Ratio',
    exportCsv: 'Export CSV',
    grossVolume: 'Gross Products Sold',
    grossVolumeDesc: 'Total sale volume from orders',
    adminSharePayout: 'Admin Share Payout',
    adminSharePayoutDesc: 'Allocated to product sellers',
    superAdminShare: 'Super-Admin Platform Share',
    superAdminShareDesc: 'Platform operational commission',
    commissionRule: 'Commission Rule',
    commissionRuleDesc: 'Active ratio split rule',
    allTransactions: 'All Transactions',
    orderTransactions: 'Online / Order Sales',
    directSalesTransactions: 'Direct WhatsApp Sales',
    searchPlaceholder: 'Search by product name, order ID, or admin...',
    emptyTitle: 'No Ledger Entries Found',
    emptyDesc: 'Revenue entries are automatically created when orders are fulfilled.',
  },

  activity: {
    title: 'Product Operations & System Audit Log',
    subtitle:
      'Chronological tracking of product creations, updates, inventory changes, and deletions across the catalog.',
    allTab: 'All Actions',
    createdTab: 'Created',
    updatedTab: 'Updated',
    deletedTab: 'Deleted',
    stockTab: 'Stock Changes',
    searchPlaceholder: 'Search activity by product name, code, or user...',
    emptyTitle: 'No Activity Logs Recorded',
    emptyDesc: 'Administrative events and catalog actions will appear here in real-time.',
  },

  forms: {
    title: 'Google Forms & Inquiries',
    subtitle:
      'Manage your external Google Forms for custom bridal bangle requests, bulk orders, and customer feedback.',
    openGoogleForm: 'Open Google Form',
    connectedStatus: 'Google Form Connected',
    changeUrl: 'Change URL',
    viewForm: 'View Form',
    livePreviewTitle: 'Live Form Preview',
    integrationBadge: 'Google Forms Integration',
    emptyTitle: 'Google Forms Tab',
    emptyDesc:
      'This tab is reserved for your Google Form. You can link any Google Form for custom customer bangle orders, bridal customization requests, or feedback surveys.',
    urlPlaceholder: 'https://docs.google.com/forms/d/e/.../viewform',
    updateButton: 'Update Form Link',
    connectButton: 'Connect Google Form',
    cancelButton: 'Cancel',
    cleanLightweightBadge: 'Currently kept clean and lightweight as requested',
    unlinkedToast: 'Google Form unlinked',
    savedToast: 'Google Form link saved successfully!',
  },

  commissionSettings: {
    title: 'Platform Revenue Split Configuration',
    subtitle:
      'Configure default profit allocation ratios between Admins (Vendors) and SuperAdmin (Platform). Default: 70% / 30%.',
    loadingConfig: 'Loading commission configuration...',
    adminSharePercentage: 'Admin Share Percentage',
    adminShareDesc: 'Percentage allocated to the product creator / seller.',
    superAdminSharePercentage: 'SuperAdmin Share Percentage',
    superAdminShareDesc: 'Percentage allocated to SuperAdmin platform fees.',
    splitCheckTitle: 'Total Split Allocation Check',
    splitCheckValid: (adminPct: number, superPct: number) =>
      `${adminPct}% Admin + ${superPct}% SuperAdmin = 100% Valid`,
    saveButton: 'Save Commission Split',
    savingButton: 'Saving...',
    sumValidationToast: 'Percentages must sum up to exactly 100%.',
    updateSuccessToast: 'Platform commission settings updated successfully!',
    updateFailedToast: 'Failed to update commission settings.',
  },

  customers: {
    title: 'Customer Directory',
    subtitle: 'Registered customers on the Sofiya Bangles mobile app and web platform.',
    totalCustomersPrefix: (total: number) => `Total Customers: ${total}`,
    searchPlaceholder: 'Search customers by full name, email, or phone number...',
    searchBtn: 'Search',
    loading: 'Loading customer accounts...',
    empty: 'No registered customers found.',
    tableCustomer: 'Customer',
    tableEmail: 'Contact Email',
    tablePhone: 'Phone',
    tableMemberSince: 'Member Since',
    tableRole: 'Account Role',
    tableAction: 'Action',
    customerRoleBadge: 'Customer',
    guestCustomer: 'Guest Customer',
    noEmail: 'No email',
    detailsBtn: 'Details',
    modalProfileTitle: 'Customer Profile',
    modalUserId: 'User ID',
    modalEmail: 'Email',
    modalPhone: 'Phone',
    modalRegDate: 'Registration Date',
    modalCloseBtn: 'Close',
    notProvided: 'Not provided',
    unknownDate: 'Unknown',
  },

  productsAnalytics: {
    title: 'Products Financial Analytics',
    subtitle:
      'Individual product sales, stock levels, and SuperAdmin 30% revenue share breakdown.',
    exportCsv: 'Export Products CSV',
    tabAll: 'All Products',
    tabBestSellers: 'Best Sellers',
    tabLowStock: 'Low Stock Alert',
    tabOutOfStock: 'Out of Stock',
    tabUnsold: 'Unsold Items',
    loading: 'Loading product analytics...',
    empty: 'No products match this filter.',
    tableProduct: 'Product',
    tableCode: 'Code',
    tablePrice: 'Price',
    tableStock: 'Stock',
    tableGrossRevenue: 'Gross Revenue',
    tableAdminShare: 'Admin 70%',
    tableSuperAdminShare: 'SuperAdmin 30%',
    tableDrilldown: 'Drilldown',
    drilldownAction: 'Drilldown',
    leftSuffix: 'left',
  },

  salesManagement: {
    title: 'Sales & Orders Management',
    subtitle:
      'Complete list of all store sales with real-time 70/30 commission allocation breakdown.',
    exportCsv: 'Export CSV',
    searchPlaceholder: 'Search by order number or customer...',
    statusLabel: 'Status:',
    allStatuses: 'All Statuses',
    statusPending: 'Pending',
    statusProcessing: 'Processing',
    statusConfirmed: 'Confirmed',
    statusCompleted: 'Completed',
    statusReturned: 'Returned / Refunded',
    loading: 'Loading sales data...',
    empty: 'No sales records found.',
    tableOrderNumber: 'Order Number',
    tableDate: 'Date',
    tableCustomer: 'Customer',
    tableTotal: 'Total Amount',
    tableAdminShare: 'Admin (70%)',
    tableSuperAdminShare: 'SuperAdmin (30%)',
    tableStatus: 'Status',
    tableAction: 'Action',
    actionDetails: 'Details',
  },

  settings: {
    title: 'Settings & Preferences',
    subtitle: 'Manage your account, platform commission rules, and store configuration',
    myProfile: 'My Profile',
    myProfileDesc: 'Manage profile picture, name & contact info',
    storeProfile: 'Store Profile',
    storeProfileDesc: 'Edit name, description, location & hours',
    security: 'Account Security & 2FA',
    securityDesc: 'Review 2-step verification, password & active sessions',
    commissionSplit: '70/30 Platform Commission Split',
    commissionSplitDesc: 'Configure profit allocation ratio between Admins and SuperAdmin',
    superAdminOnlyBadge: 'SuperAdmin Only',
  },
} as const;


